name = "TableIO"
uuid = "8545f849-0b94-433a-9b3f-37e40367303d"
authors = ["Benjamin Lungwitz <benj.lung@googlemail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
